"""
Remove worksheet-level <filter> blocks that reference orphan auto-generated
groups: Action (Statut Global), Inclusions (...), Tooltip (Projet).

These filters are auto-generated by Tableau when dashboards have Filter/Highlight
Actions. They get re-created when the user opens the dashboard, so removing them
is safe.

Also remove the corresponding <column> entries in <slices> blocks.
"""
import zipfile, shutil, re
from pathlib import Path

TWBX_PATH = Path(r"C:\Users\quinson\Desktop\Claude\Dasboard suivi projet DataWarehouse.twbx")
WORK_DIR = Path(r"C:\Users\quinson\Desktop\Claude\Tableau DWH\twbx_remove_filters")

# The 3 orphan group field names
ORPHAN_GROUPS = [
    "Action (Statut Global)",
    "Inclusions (Date d&apos;\u00e9ch\u00e9ance,Description source,Intervenant 1,Intervenant 2,Nom rapport,Nom source)",
    "Tooltip (Projet)",
]

if WORK_DIR.exists():
    shutil.rmtree(WORK_DIR)
WORK_DIR.mkdir()
with zipfile.ZipFile(TWBX_PATH, 'r') as z:
    z.extractall(WORK_DIR)
twb_file = next(WORK_DIR.glob("*.twb"))
content = twb_file.read_text(encoding='utf-8')
orig_len = len(content)

for g in ORPHAN_GROUPS:
    g_escaped = re.escape(g)
    # Match <filter ... column='[<ds>].[<group>]'>...</filter> blocks
    filter_pattern = (
        r"\s*<filter [^>]*column='\[federated\.[^]]+\]\.\[" + g_escaped +
        r"\]'>[^<]*(?:<[^/][^<]*</[^>]*>[^<]*)*</filter>\r?\n"
    )
    # Simpler pattern: greedy match until closing </filter>
    simpler = r"\s*<filter [^>]*\[" + g_escaped + r"\][^>]*>.*?</filter>\r?\n"
    n_f = len(re.findall(simpler, content, re.DOTALL))
    content = re.sub(simpler, "\n", content, flags=re.DOTALL)
    print(f"Removed {n_f} <filter> blocks for [{g}]")

    # Remove <column>...</column> in slices that reference the group
    col_in_slice = r"\s*<column>\[federated\.[^]]+\]\.\[" + g_escaped + r"\]</column>\r?\n"
    n_c = len(re.findall(col_in_slice, content))
    content = re.sub(col_in_slice, "\n", content)
    print(f"Removed {n_c} <column> in slices for [{g}]")

print(f"\nLength: {orig_len} -> {len(content)} (delta: {len(content)-orig_len})")

twb_file.write_text(content, encoding='utf-8')

import xml.etree.ElementTree as ET
try:
    ET.parse(twb_file)
    print("XML: VALID")
except ET.ParseError as e:
    print(f"XML PARSE ERROR: {e}")
    raise SystemExit(1)

# Repackage
tmp_twbx = TWBX_PATH.parent / "twbx_tmp.twbx"
if tmp_twbx.exists():
    tmp_twbx.unlink()
with zipfile.ZipFile(tmp_twbx, 'w', zipfile.ZIP_DEFLATED) as z:
    for f in WORK_DIR.rglob('*'):
        if f.is_file():
            z.write(f, arcname=f.relative_to(WORK_DIR))
shutil.copy2(tmp_twbx, TWBX_PATH)
tmp_twbx.unlink()
shutil.rmtree(WORK_DIR)
print(f"Repackaged: {TWBX_PATH}")
